---
- name: Add Linux host as node to Solarwinds
  hosts: localhost
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3.11
    solarwinds_server: pwnc0429swmpe01.bdx.com
    solarwinds_username: TEST_AUTOMATION
    solarwinds_password: ghk4*kcd$!jf%
    orion_node_ip_address: "{{ orion_node_ip_address }}"
    orion_node_caption_name: "{{ orion_node_caption_name }}"
    orion_node_polling_method: SNMP
    orion_node_sys_name: "{{ orion_node_caption_name }}"
    orion_node_machine_name: "{{ orion_node_machine_name }}"
    orion_node_vendor_name: "{{ orion_node_vendor_name }}"
    orion_node_snmp_version: 3
    orion_node_snmpv3_username: bdsnmp3roadmin
    orion_node_snmpv3_auth_key: GkqS2435+QvjL3895@
    orion_node_snmpv3_auth_method: MD5
    orion_node_snmpv3_priv_key: GkqS2435+QvjL3895@
    orion_node_snmpv3_credential_set: 49
    orion_node_snmpv3_priv_method: None
    orion_node_discover_interfaces: false
    orion_node_interfaces: "GigabitEthernet1/0/1,GigabitEthernet1/0/2,StackPort1"
    orion_node_snmp_pollers:
      - name: N.LoadAverage.SNMP.Linux
        enabled: true
      - name: N.Cpu.SNMP.HrProcessorLoad
        enabled: true
      - name: N.Memory.SNMP.NetSnmpReal
        enabled: true
      - name: N.Status.ICMP.Native
        enabled: true
      - name: N.Uptime.SNMP.Generic
        enabled: true
      - name: N.Topology_Layer3.SNMP.ipNetToMedia
        enabled: true
      - name: N.Details.SNMP.Generic
        enabled: true

  roles:
    - { role: solarwinds.orion.orion_node }
