---
- name: Add Linux host as node to Solarwinds
  hosts: localhost
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
    solarwinds_server: 10.67.143.11
    solarwinds_username: TEST_AUTOMATION
    solarwinds_password: ghk4*kcd$!jf%
    orion_node_ip_address: 10.191.135.4
    orion_node_caption_name: BRA34A-IDF10-AS11
    orion_node_polling_method: SNMP
    orion_node_sys_name: BRA34A-IDF10-AS11
    orion_node_machine_name: C9300-48U
    orion_node_vendor_name: Cisco
    orion_node_snmp_version: 3
    orion_node_snmpv3_username: bdsnmp3roadmin
    orion_node_snmpv3_auth_key: GkqS2435+QvjL3895@
    orion_node_snmpv3_auth_method: MD5
    orion_node_snmpv3_priv_key: GkqS2435+QvjL3895@
    orion_node_snmpv3_credential_set: 74
    orion_node_snmpv3_priv_method: None
    orion_node_discover_interfaces: True
    orion_node_interfaces: "Ten 2/1/1,Ten 1/1/1"
    orion_node_snmp_pollers:
      - name: N.LoadAverage.SNMP.Linux
        enabled: true
      - name: N.Cpu.SNMP.HrProcessorLoad
        enabled: true
      - name: N.Memory.SNMP.NetSnmpReal
        enabled: true

  roles:
    - { role: solarwinds.orion.orion_node }
