---
- name: Add Linux host as node to Solarwinds
  hosts: localhost
  gather_facts: false # if you don't want to use ansible facts, make sure to then override default caption and IP variables
  vars:
    ansible_python_interpreter: /usr/bin/python3
    solarwinds_server: 10.190.16.65
    solarwinds_username: TEST_AUTOMATION
    solarwinds_password: ghk4*kcd$!jf%
    orion_node_ip_address: "{{ orion_node_ip_address }}"
    orion_node_caption_name: "{{ orion_node_caption_name }}" 
    orion_node_polling_method: "{{ orion_node_polling_method }}"
    orion_node_sys_name: "{{ orion_node_sys_name }}"
    orion_node_machine_name: "{{ orion_node_machine_name }}"
    orion_node_vendor_name: "{{ orion_node_vendor_name }}"
    orion_node_snmp_version: 3
    orion_node_snmpv3_username: bdsnmp3roadmin
    orion_node_snmpv3_auth_key: GkqS2435+QvjL3895@
    orion_node_snmpv3_auth_protocol: MD5
    orion_node_snmpv3_priv_key: "{{ orion_node_snmpv3_priv_key }}" # Replace with your SNMPv3 privacy key if required
    orion_node_snmpv3_priv_protocol: DES # Replace with your desired SNMPv3 privacy protocol if required
    snmpv3_auth_method: MD5
    snmpv3_auth_key_is_pwd": GkqS2435+QvjL3895@
    snmpv3_priv_method: null
    snmpv3_priv_key_is_pwd: GkqS2435+QvjL3895@
    snmpv3_username: bdsnmp3roadmin
    orion_node_discover_interfaces: true
    orion_node_snmp_pollers:
      - name: N.LoadAverage.SNMP.Linux
        enabled: true
      - name: N.Cpu.SNMP.HrProcessorLoad
        enabled: true
      - name: N.Memory.SNMP.NetSnmpReal
        enabled: true

  roles:
     - { role: solarwinds.orion.orion_node }
