- name: Ensure necessary packages are installed in Minikube
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Check if python3.10 exists
      stat:
        path: /usr/bin/python3
      register: python_check

    - name: Show Python version
      command: "{{ ansible_python_interpreter }} --version"
      register: python_version

    - debug:
        var: python_version

    - name: Show installed packages
      command: "{{ ansible_python_interpreter }} -m pip list"
      register: pip_list

    - debug:
        var: pip_list

    - name: Install orionsdk python package on version 0.3.0
      ansible.builtin.pip:
        name: orionsdk==0.3.0
