---
- name: Verify orionsdk installation and execute task
  hosts: wsl
  vars:
    ansible_python_interpreter: /usr/bin/python3.10
  tasks:
    - name: Show Python version
      command: "{{ ansible_python_interpreter }} --version"
      register: python_version
    - debug:
        var: python_version

    - name: Show installed packages
      command: "{{ ansible_python_interpreter }} -m pip list"
      register: pip_list
    - debug:
        var: pip_list
