- name: Ensure sudo and python3.10 are installed
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Check if sudo exists
      stat:
        path: /usr/bin/sudo
      register: sudo_check

    - name: Check if python3.10 exists
      stat:
        path: /usr/bin/python3.10
      register: python_check

    - name: Show Python version
      command: "{{ ansible_python_interpreter }} --version"
      register: python_version

    - debug:
        var: python_version

    - name: Show installed packages
      command: "{{ ansible_python_interpreter }} -m pip list"
      register: pip_list

    - debug:
        var: pip_list
