- name: Ensure sudo and python3.10 are installed
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Check if sudo exists
      stat:
        path: /usr/bin/sudo
      register: sudo_check

    - name: Check if python3.10 exists
      stat:
        path: /usr/bin/python3
      register: python_check

    - name: Show Python version
      command: "{{ ansible_python_interpreter }} --version"
      register: python_version

    - debug:
        var: python_version

    - name: Show installed packages
      command: "{{ ansible_python_interpreter }} -m pip list"
      register: pip_list

    - debug:
        var: pip_list

    - name: Check if pip3 exists
      stat:
        path: /usr/bin/pip3
      register: pip3_check

    - name: Install pip3 if not present
      package:
        name: python3-pip
        state: present
      when: not pip3_check.stat.exists

    - name: Install orionsdk==0.3.0 using pip3
      pip:
        name: orionsdk==0.3.0
        executable: "/usr/bin/pip3"
      when: pip3_check.stat.exists

    - name: Install orionsdk==0.3.0 using pip module if pip3 was just installed
      pip:
        name: orionsdk==0.3.0
      when: not pip3_check.stat.exists
