---
- name: Ping Test Playbook
  hosts: cisco_routers
  gather_facts: no
  tasks:
    - name: Get facts from Cisco IOS devices
      cisco.ios.ios_facts:
      register: cisco_facts
 
    - name: Display gathered facts
      ansible.builtin.debug:
        var: cisco_facts
 
    - name: Display all gathered facts
      ansible.builtin.debug:
        var: ansible_facts
        
    - name: Run show version on remote devices
      cisco.ios.ios_command:
        commands: show version
      register: version_output

    - name: Display show version output
      ansible.builtin.debug:
        var: version_output  
