---
- name: Verify orionsdk installation and execute task
  hosts: wsl
  vars:
    ansible_python_interpreter: /usr/bin/python3.10
  tasks:
    - name: Ensure orionsdk is installed
      command: /usr/bin/python3.10 -m pip show orionsdk
      register: orionsdk_check
      ignore_errors: yes

    - name: Install orionsdk if not present
      pip:
        name: orionsdk
        state: present
      when: orionsdk_check.rc != 0
